### ISSUE TITLE
关于命名的问题

### ISSUE THREAD

**Issue by meimisaki** [tioover/sansa#1]
蒟蒻一只。。知乎上看到菊苣的blog然后戳进这个repo的。。

根目录里和src/resource.rs里的Assert是不是命名错误呀？。。
窝觉得大概是Assets？

（要是是窝误解了就Close掉吧。。QAQ

PS：
看了下代码发现，似乎rust的GL Binding做得挺好用呀。。

<del>不像haskell的，坑不少。。比如没有Matrix4x4没有Uniform的instance。。得回去用OpenGLRaw。。</del>

**Comment by tioover** [comment]
谢谢！我英语烂2333
这个 GL Binding 太好用了……真的非常好用
